name: 'IaC AWS ➜ Apply'
 
run-name: IaC AWS ➜ Apply | ${{ github.event.inputs.environment }}
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to DEPLOY'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

permissions:
 id-token: write
 contents: read
 
jobs:
  set-role:
    runs-on:
      group: AWS
      labels: ubuntu-latest
    outputs:
      role: ${{ steps.map.outputs.role }}
    steps:
      - id: map
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "role=" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.environment }}" = "hmg" ]; then
            echo "role=" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.environment }}" = "prd" ]; then
            echo "role=" >> $GITHUB_OUTPUT
          else
            echo "Ambiente inválido"; exit 1
          fi
  call-reusable-workflow:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: 'IaC'
    needs: [set-role]
    uses: moraes-caroline/iac-reusable-aws/.github/workflows/reusable-apply.yaml@main
    with:
      environment: '${{ github.event.inputs.environment }}'
      terraform_directory: '.'
      role-to-assume: '${{ needs.set-role.outputs.role }}'
    secrets: inherit
