name: 'IaC AWS ➜ Plan'
 
run-name: IaC AWS ➜ Plan | ${{ github.event.inputs.environment }}
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to DEPLOY'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev    
jobs:
  set-role:
    runs-on:
      group: AWS
      labels: [self-hosted, Linux, X64, aws, aws-1]

 
    outputs:
      role: ${{ steps.map.outputs.role }}
    steps:
      - id: map
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "role=arn:aws:iam::524558748007:role/role-terraform-aws" >> $GITHUB_OUTPUT
          else
            echo "Ambiente inválido"; exit 1
          fi
 
  call-reusable-workflow:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: 'IaC'
    needs: [set-role]
    uses: moraes-caroline/iac-reusable-aws/.github/workflows/reusable-plan.yml@main
    with:
      environment: '${{ github.event.inputs.environment }}'
      terraform_directory: '.'
      role-to-assume: '${{ needs.set-role.outputs.role }}'
    secrets: inherit
